In [1]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import string
import nltk
nltk.download('stopwords')
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords
from __future__ import print_function
import os
import sys
from keras.models import Sequential
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from keras.layers import Dense,LSTM, Input, GlobalMaxPooling1D,Flatten,Activation
from keras.layers import Conv1D, MaxPooling1D, Embedding
from keras.models import Model
from keras.initializers import Constant

[nltk_data] Downloading package stopwords to /home/priya/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Using TensorFlow backend.


In [5]:
data = pd.read_csv("./Data/phrases.csv")
# data=pd.DataFrame(data)
data = data.dropna()
print(data['Emotion'].unique())

['joy' 'fear' 'anger' 'sadness' 'disgust' 'shame' 'guilt']


In [6]:
def clean_dataset(data):
    translator = string.maketrans('', '')
    for index,row in data.iterrows():
        row['Phrase'] = row['Phrase'].replace('[','')
        row['Phrase'] = row['Phrase'].replace(']','')
        row['Phrase'] = row['Phrase'].strip()
        row['Phrase'] = row['Phrase'].translate(translator,string.punctuation)
    return data
data = clean_dataset(data)
data.head()

Emotion                                             Phrase
0      joy  On days when I feel closing to my partner and ...
1     fear  Every time I imagine that someone I love or I ...
2    anger  When I had been obviously unjustly treated and...
3  sadness  When I think about the short time that we live...
4  disgust  At a gathering I found myself involuntarily si...

In [7]:
def tokenise(data):
    ## Convert words to lower case and split them    
    ## Remove stop words
    stops = set(stopwords.words("english"))
    
    for index,row in data.iterrows():
        text = row['Phrase'].lower().split(' ')
        text = [w.strip() for w in text if not w in stops and len(w) >= 2]
        text = " ".join(text)
        row['Phrase'] = text
    # split the dataset into tokens
    return data
data = tokenise(data)
data.head()

Emotion                                             Phrase
0      joy  days feel closing partner friends when feel pe...
1     fear  every time imagine someone love could contact ...
2    anger  obviously unjustly treated possibility of eluc...
3  sadness  think short time live relate the periods life ...
4  disgust  gathering found involuntarily sitting next two...

In [8]:
def lemmatization(dataset):
    stemmer = SnowballStemmer('english')
    list_of_words=[]
    for index,row in dataset.iterrows():
        text = row['Phrase'].split()
        stemmed_words = [stemmer.stem(word) for word in text]
        list_of_words.append(stemmed_words)
        text = " ".join(stemmed_words)
        row['Phrase'] = text
    data['list_of_words'] = list_of_words
    return dataset
data = lemmatization(data)
data.head()

Emotion                                             Phrase  \
0      joy  day feel close partner friend when feel peac a...   
1     fear  everi time imagin someon love could contact se...   
2    anger             obvious unjust treat possibl of elucid   
3  sadness  think short time live relat the period life th...   
4  disgust  gather found involuntarili sit next two peopl ...   

                                       list_of_words  
0  [day, feel, close, partner, friend, when, feel...  
1  [everi, time, imagin, someon, love, could, con...  
2      [obvious, unjust, treat, possibl, of, elucid]  
3  [think, short, time, live, relat, the, period,...  
4  [gather, found, involuntarili, sit, next, two,...

In [9]:
# def tokenize(text):
MAX_SEQUENCE_LENGTH = 50

tokenizer = Tokenizer()
tokenizer.fit_on_texts(data['Phrase'])

token_tr_X = tokenizer.texts_to_sequences(data['Phrase'])
x_train_text = []

x_train_text = pad_sequences(token_tr_X, maxlen=MAX_SEQUENCE_LENGTH)
#     return x_train_text,tokenizer
# x_train_text,tokenizer = tokenize(data['Phrase'])

In [10]:
import codecs
EMBEDDING_DIM = 300

word_index = tokenizer.word_index
print('Found %s unique tokens' % len(word_index))

file_loc = './glove.6B/glove.6B.300d.txt'

print (file_loc)

gembeddings_index = {}
with codecs.open(file_loc, encoding='utf-8') as f:
    for line in f:
        values = line.split(' ')
        word = values[0]
        gembedding = np.asarray(values[1:], dtype='float32')
        gembeddings_index[word] = gembedding
#
f.close()
print('G Word embeddings:', len(gembeddings_index))

nb_words = len(word_index) +1
g_word_embedding_matrix = np.zeros((nb_words, EMBEDDING_DIM))
for word, i in word_index.items():
    gembedding_vector = gembeddings_index.get(word)
    if gembedding_vector is not None:
        g_word_embedding_matrix[i] = gembedding_vector
        
print('G Null word embeddings: %d' % np.sum(np.sum(g_word_embedding_matrix, axis=1) == 0))

Found 6538 unique tokens
./glove.6B/glove.6B.300d.txt
G Word embeddings: 400000
G Null word embeddings: 2388


In [11]:
from sklearn.preprocessing import label_binarize
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
Y=(data['Emotion']).tolist()
Y = lb.fit_transform(Y)

# for ses_mod in data:
#     Y.append(ses_mod['Emotion'])
    
# Y = label_binarize(Y,(data['Emotion'].unique()).tolist())

Y.shape
print(Y)

[[0 0 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
