In [80]:
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import string
import nltk
nltk.download('stopwords')
from nltk.stem import SnowballStemmer
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /home/himani/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [81]:
# normalisation of the dataset
def normalize(X):
    from sklearn.preprocessing import StandardScaler
    X = StandardScaler().fit_transform(X)
    return X

In [82]:
#read the data set
data = pd.read_csv("./Data/phrases.csv")
# data=pd.DataFrame(data)
# print type(data)
print data['Emotion'].unique()

['joy' 'fear' 'anger' 'sadness' 'disgust' 'shame' 'guilt']


## We are applying an LSTM based model for the emotion prediction. a special kind of RNN, capable of learning long-term dependencies.

## Preprocess the data set via cleaning, tokenisation and lemmatization

In [83]:
# print data
def clean_dataset(data):
    translator = string.maketrans('', '')
    for index,row in data.iterrows():
        row['Phrase'] = row['Phrase'].replace('[','')
        row['Phrase'] = row['Phrase'].replace(']','')
        row['Phrase'] = row['Phrase'].strip()
        row['Phrase'] = row['Phrase'].translate(translator,string.punctuation)
    return data
data = clean_dataset(data)
print data.head()

   Emotion                                             Phrase
0      joy  On days when I feel closing to my partner and ...
1     fear  Every time I imagine that someone I love or I ...
2    anger  When I had been obviously unjustly treated and...
3  sadness  When I think about the short time that we live...
4  disgust  At a gathering I found myself involuntarily si...


In [84]:
def tokenise(data):
    ## Convert words to lower case and split them    
    ## Remove stop words
    stops = set(stopwords.words("english"))
    
    for index,row in data.iterrows():
        text = row['Phrase'].lower().split(' ')
        text = [w.strip() for w in text if not w in stops and len(w) >= 2]
        text = " ".join(text)
        row['Phrase']=text
    # split the dataset into tokens
    return data
data = tokenise(data)
data.head()

Emotion                                             Phrase
0      joy  days feel closing partner friends when feel pe...
1     fear  every time imagine someone love could contact ...
2    anger  obviously unjustly treated possibility of eluc...
3  sadness  think short time live relate the periods life ...
4  disgust  gathering found involuntarily sitting next two...

In [85]:
def lemmatization(dataset):
    stemmer = SnowballStemmer('english')
    list_of_words=[]
    for index,row in dataset.iterrows():
        text = row['Phrase'].split()
        stemmed_words = [stemmer.stem(word) for word in text]
        list_of_words.append(stemmed_words)
        text = " ".join(stemmed_words)
        row['Phrase'] = text
    data['list_of_words'] = list_of_words
    return dataset
data = lemmatization(data)
data

Emotion                                             Phrase  \
0         joy  day feel close partner friend when feel peac a...   
1        fear  everi time imagin someon love could contact se...   
2       anger             obvious unjust treat possibl of elucid   
3     sadness  think short time live relat the period life th...   
4     disgust  gather found involuntarili sit next two peopl ...   
5       shame  realiz direct feel discont with partner way tr...   
6       guilt  feel guilti realiz consid materi thing more im...   
7         joy            girlfriend taken exam went parent place   
8        fear                       first time realiz mean death   
9       anger                  car overtak anoth forc drive road   
10    sadness  recent thought hard work take studi how one wa...   
11    disgust                       found bristl liver past tube   
12      shame  tire unmotiv shout girlfriend and brought nega...   
13      guilt  think studi enough weekend think abl accomplis...   
14        joy                             pass examin think well   
15       fear  one arrang meet someon person arriv late meant...   
16      anger                   one unjust accus someth one done   
17    sadness       one studi seem hopeless difficult uninterest   
18    disgust  one find someon know like one had thought inst...   
19      shame                one unjust stupid toward someon els   
20      guilt                     one neglect unjust good friend   
21        joy                              pass exam expect pass   
22       fear  climb tree pick appl angl ladder i enabl get h...   
23      anger                                 friend tortur anim   
24    sadness                                              anger   
25    disgust                                 friend tortur anim   
26      shame                                 friend tortur anim   
27      guilt                                excus necessari get   
28        joy                                           children   
29       fear  year old son climb sat 7th floor balconi leg h...   
...       ...                                                ...   
7622    shame                     forgot zip trouser notic anyon   
7623    guilt                                               peep   
7624      joy                 picnic old classmat chat play game   
7625     fear  night alon home famili member usual get togeth...   
7626    anger  saw bed hostel mess guess someon els use daili...   
7627  sadness  physic experi session understand content exper...   
7628  disgust  man sexual aggress small girl bus girl not dar...   
7629    shame                                unabl stop urin bus   
7630    guilt  old peopl crowd bus courag give seat close eye...   
7631      joy  first time gave birthday present friend wrote ...   
7632     fear  week higher level result announc had tri fail ...   
7633    anger  surnam brother differ often grin home provok o...   
7634  sadness  primari father die young and know happen weep ...   
7635  disgust  hostel roommat selfish person would avoid do a...   
7636    shame  friend mani femal friend thought his lover wou...   
7637    guilt  past use think mother nag person start live ho...   
7638      joy  august1983 long await big envelop document cuh...   
7639     fear  christma eve1984 finish exam afraid result one...   
7640    anger  septemb 1984 forc live someon like first week ...   
7641  sadness  issu worri rather sadden mid septemb i went gu...   
7642  disgust  roommat like listen meaningless song melodi co...   
7643    shame  last summer went camp cu student work leav sec...   
7644    guilt                                lie one best friend   
7645      joy                       receiv letter distant friend   
7646     fear  parent eldest home midnight male stranger phon...   
7647    anger  two year back someon invit tutor granddaught g...   
7648  sadness  taken respons someth prepar howev fail timid t.

In [96]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding
vocabulary_size = 20000
tokenizer = Tokenizer(num_words= vocabulary_size)
tokenizer.fit_on_texts(data['Phrase'])

sequences = tokenizer.texts_to_sequences(data['Phrase'])
tokenized_data = pad_sequences(sequences, maxlen=10)
# tokenized_data


In [97]:
from sklearn.preprocessing import OneHotEncoder
# enc = OneHotEncoder(handle_unknown='ignore')
# X = data['Emotion'].unique()
# # print X
# X=X.reshape(-1,1)
# # print X
# enc.fit(X)
# enc.categories_
emotion_data=data['Emotion'].values
# emotion_data=emotion_data.reshape(-1,1)
# emotion_data=enc.transform(emotion_data).toarray()

print emotion_data

# Import LabelEncoder
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
emo_enc=le.fit_transform(emotion_data)
print emo_enc


['joy' 'fear' 'anger' ... 'disgust' 'shame' 'guilt']
[4 2 0 ... 1 6 3]


In [98]:
train_phrase, validate_phrase = np.split(tokenized_data,[int(.8*len(tokenized_data))])
# train_label,validate_label=np.split(emotion_data,[int(.8*len(emotion_data))])
train_label,validate_label=np.split(emo_enc,[int(.8*len(emo_enc))])
train_label

array([4, 2, 0, ..., 6, 3, 4])

In [99]:
# Using sklearn's Multinomial Naive Bayes
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score

clf = MultinomialNB()
clf.fit(train_phrase,train_label)
Y_test_pred = clf.predict(validate_phrase)
print Y_test_pred
sklearn_score_train = clf.score(train_phrase,train_label)
print("Sklearn's score on training data :",sklearn_score_train)
sklearn_score_test = clf.score(validate_phrase,validate_label)
print("Sklearn's score on testing data :",sklearn_score_test)
print("Classification report for testing data :-")
print(classification_report(validate_label, Y_test_pred))


from sklearn.metrics import accuracy_score
roc_auc_score(Y_test_pred, validate_label)

[5 0 2 ... 4 4 6]
("Sklearn's score on training data :", 0.16614932200620813)
("Sklearn's score on testing data :", 0.14435009797517961)
Classification report for testing data :-
              precision    recall  f1-score   support

           0       0.15      0.09      0.11       219
           1       0.11      0.19      0.14       220
           2       0.16      0.21      0.18       219
           3       0.10      0.03      0.04       218
           4       0.16      0.31      0.21       218
           5       0.15      0.13      0.14       218
           6       0.19      0.06      0.10       219

   micro avg       0.14      0.14      0.14      1531
   macro avg       0.15      0.14      0.13      1531
weighted avg       0.15      0.14      0.13      1531



ValueError: multiclass format is not supported